POST http://localhost:8080/v1/features
Content-Type: application/json

{"technicalName" : "TechnicalName-1",
"displayName": "Feature 1",
"Description": "Description for Feature 1",
"enabled": true,
"expiration": "2023-03-30T00:00:00Z",
"customerIds": ["121", "124", "125"]}

###
GET http://localhost:8080/v1/features?customerId=145

###
GET http://localhost:8080/v1/features/63e4b63cffc82e4031799b85

###
DELETE http://localhost:8080/v1/features/63e50deffee3ee0f04a3501f