spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: feature-management-db
      username: username
      password: password
      authentication-database: admin
      auto-index-creation: true