version: '3'

services:

  mongodb:
    image: 'mongo:6'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: feature-management-db
#    volumes:
#      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - feature-management

  backend:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - feature-management

  frontend:
    build: ../angular/feature-management-gui
    ports:
      - "4200:4200"
    networks:
      - feature-management

networks:
  feature-management:
    driver: bridge
